name: 2. Build and Publish

on:
  workflow_run:
    workflows: ["1. Bump Version"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - "v*.*.*"

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build reward-app
        run: |
          ./services/rewarding/scripts/build.sh -c -u -g=${{ secrets.IMG_REGISTRY }}
      - name: Build validator
        run: |
          ./neurons/validator/scripts/build.sh -c -u -g=${{ secrets.IMG_REGISTRY }}
      - name: Build miner
        run: |
          ./neurons/miner/scripts/build.sh -c -u -g=${{ secrets.IMG_REGISTRY }}
      - name: Trigger release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run 3.create-release.yml
